import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header/Header";
import MobileSideBar from './components/ui/sidebar/MobileSideBar';



const geistLato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistLato.variable} h-full antialiased`}
    >
      <body className="">
        <Header />
        <MobileSideBar/>
        {children}</body>
    </html>
  );
}
